apiBaseUrl=http://localhost:4111
apiVersion=/api/v1

admin.login=admin
admin.password=admin

uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://192.168.0.168:3000
browser = chrome
browserSize = 1920x1080
