apiBaseUrl=http://localhost:4111
apiVersion=/api/v1
api.version=with_fraud_check_with_transfer_fix
#possible values: with_validation_fix, with_database, with_fraud_check_with_transfer_fix

admin.login=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://host.docker.internal:3000
browser=chrome
browserSize=1920x1080

db.url=jdbc:postgresql://localhost:5432/nbank
db.username=postgres
db.password=postgres