apiBaseUrl=http://localhost:4111
apiVersion=/api/v1
api.version=with_database
//?????:with_validation_fix, with_database

admin.login=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://host.docker.internal:3000
browser=chrome
browserSize=1920x1080

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres