# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CreateUserRequest=CreateUserResponse:username=username,role=role
TransferRequest=TransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount

# for expected = result comparison
TransferResponse=TransferResponse:status=status,message=message,amount=amount,senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,fraudRiskScore=fraudRiskScore,fraudReason=fraudReason,requiresManualReview=requiresManualReview,requiresVerification=requiresVerification