POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

//описала кейсы в постмане, тк не работал http client для community edition
