### Get auth token
### Admin Token: Authorization: Basic YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate19981",
  "password": "kate19981"
}

### Positive test: Admin can create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19981",
  "password": "kate19981",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank username
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "  ",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2  or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "ab",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2 or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "abcdefghfhfhffhr",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username contains $%^&*()@# characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "$%^&*()@#",
  "password": "{{$random.uuid}}",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank password
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user123423e",
  "password": "dddDaaa13!$",
  "role": "EDITOR"
}

### Negative test: Admin cannot create new user with password less than 8 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "1234567",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password without digits
### Negative test: Admin cannot create new user with password without one lower case character
### Negative test: Admin cannot create new user with password without one upper case character
### Negative test: Admin cannot create new user with password without special character
### Negative test: Admin cannot create new user with password with spaces
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "1234567",
  "role": "USER"
}

### Negative test: Admin cannot create new user with role not from list "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "{{$random.uuid}}",
  "password": "{{$random.uuid}}",
  "role": "EDITOR"
}

### Negative test: Create user that already exists by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "kate1998",
  "role": "USER"
}


### Positive test: Authorized user can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Positive test: check account was created
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==